print("Nhập bốn số để tìm ra max and min trong bốn số đó:")
a = eval(input("nhập số: "))
b = eval(input("nhập số: "))
c = eval(input("nhập số: "))
d = eval(input("nhập số: "))
danh_sach = [a,b,c,d]
max_number = max(danh_sach)
min_number = min(danh_sach)
print(f"Ta có dãy số là: {danh_sach}")
print("Số lớn nhất (MAX) là:",max_number)
print("Số nhỏ nhất (MIN) là:",min_number)